flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
set FLASK_ENV=development
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
pip install flask-debugtoolbar
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
bash <(curl -s https://migration.c9.io/migrate-cs50.sh) "https://awscloud9v3downloadinfra-exportedworkspacesbucket-1ef2i5e25sllk.s3.us-east-2.amazonaws.com/exports/2291964/6547645/ide50-6547645.20190701T120218025Z.home.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIASANISPZTYOLXY2WT%2F20190701%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20190701T122045Z&X-Amz-Expires=1800&X-Amz-Security-Token=AgoJb3JpZ2luX2VjEFsaCXVzLWVhc3QtMiJIMEYCIQDwauPAEhmB2VfFugNaTP1pripxYv%2FEjHj%2FMSXc5MVvcQIhAMaO%2FQqjGo%2Bi7mlPfOvwpIjDRBy5pMspx6WjU8JwrXfQKsQCCKX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMMTM4MzI5MzU3OTI3IgxAbVKYBm%2FcAyTDDsIqmAJyTngFEEXp%2B6SFKpzO0vVizy0iQwc%2BLy6IwYS62ZNFPzZAbYQ9wdEXvRd9FJH7295KbP%2B0ulJyjfiZb6pZtoaIdgREtAGL2DjW3iwRnZoj4gqIAP7nkC0psmiOIW9fQMQox0uN4MzxwvVXpgaKwLiXZ3tG79uI%2BfNPKj%2Bf8W0HxsJH7vRI9w1jLc1dEWjdMdt2D9uPWrp35I39gwJwXLtvCSHVyJBnGaT7IzwC56sCbctmj1MpPkHQjRUqhCr0IOkCBaplY8A7Ygy9%2F5tFlNo0OuDZszWLrvkZuliQV4VAlWxO%2FlThLKf2xxJxjJqYLihBnAbIDvgd2zEH2YRTPAF4W8Kr6vETpCL08%2F8JROcGWIT13%2BjFN5B%2FMLXd5%2BgFOrMBtnP%2FSk6chRNHzNA9R4B7zypsHrzIZpL%2F78MdWV8TcldxHrQn0laLM%2BX710o7yv8ZSEhmiYHjWtn5HSmiFF5lofIRm%2BmztDg42vqY5zyceABE%2BEiCxFAh5TrfyY%2BiMmU67eIei8kAp%2FmM5uFeX0CP%2Fm9K9QDAZy0fCr5erfZc%2FDBRR0OpiskSi76A0Tsww1ubzQSqujaSCM7XaXVaMNwhHkQ1fVy8Vq7Uf%2BtoCk6zVIrDpX4%3D&X-Amz-Signature=9ffeb87d4f55692a40d2959634552cbb45068c595939078fa952b6377caf346f&X-Amz-SignedHeaders=host" "p+9eQWDi/Y6+DWq+Crcy7EH24+/oA6bG9aLh8ecA7YnS2BzqPfOG+Pi+2/4yspaN" 133 && cd $HOME/environment
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask runr
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run k
flask run
flask run
flask run
flask run
flask run
fflask run
flask run
flask run
flask run
f
fflask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
flask run
git init
git remote add origin https://github.com/bahgaat/cs50 final project.git
git commit -am "first commit"
git push -u origin master
gitinit
cd /
cd~/
cd ~/
git init
git remote add origin https://github.com/bahgaat/cs50 final project.git
git commit -am "first commit"
git push -u origin master
git remote add origin https://github.com/bahgaat/cs50-final-project.git
git push -u origin master
cd ~/
git init
git init
git remote add origin https://github.com/username/finance.git
git remote add origin https://github.com/bahgaat/cs50.git
git commit -am "first commit"
echo "# cs50-final-project" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/bahgaat/cs50-final-project.git
git push -u origin master
cd cash/
cd cash
git init
git remote add origin https://gihub.com/bahgaat/cash.git
git commit -am "second commit"
git push -u origin master
git remote -v
git branch
git push origin master
git config --global user.name bahgaat
git config --global user.password Abcdefgh491998
git push origin master
git status
gitadd .
cd environment
cd /environment
cd ..
git add --. ':!<environment>'
git ignore
git add.
git add
